

const products = {
    "12-tatcha-23": {
        "productId": "12-tatcha-23",
        "imageId": 15,
        "brand": "Tatcha",
        "type": "skincare",
        "name": "The water cream",
        "concern": "Helps reduce Dryness",
        "howToUse": "Scoop a pearl-size amount of cream with the gold spoon.Massage onto face, neck, and décolletage in upward strokes.Use daily, morning and night.",
        "ingredients": "Japanese Wild Rose,Japanese Leopard Lily,Hadasei-3",
        "price": "102.45",
        "quantity": '1',
        "maxQuantity": '1'
    },
    "13-brush-set-34": {
        "productId": "13-brush-set-34",
        "imageId": 1,
        "brand": "Sephora",
        "type": "makeup",
        "name": "Ready To Roll Brush Set",
        "concern": "Helps smooth makeup application",
        "howToUse": "No instructions available",
        "ingredients": "Nylon, Taklon and other manmade fibres",
        "price": "70.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "14-compact-powder-45": {
        "productId": "14-compact-powder-45",
        "imageId": 2,
        "brand": "Armani Beauty",
        "type": "makeup",
        "name": "Luminous Silk Compact Powder Foundation",
        "concern": "Oil control setting powder",
        "howToUse": "Apply using the included applicator. Can be worn alone or over foundation for extra coverage and shine control.",
        "ingredients": "Micro-fil Technology: Provides translucent radiance and a flawless finish.",
        "price": "64.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "15-curology-cleanser-56": {
        "productId": "15-curology-cleanser-56",
        "imageId": 3,
        "brand": "Curology",
        "type": "skincare",
        "name": "Cleanser",
        "concern": "Helps reduce uneven texture and pores",
        "howToUse": "Squeeze a small amount into palms and rub together to create a creamy foam.Gently massage the face avoiding the eye area and rinse thoroughly.",
        "ingredients": "Japanese Wild Rose,Japanese Luffa fruit Exfoliant:",
        "price": "20.00",
        "quantity": '1',
        "maxQuantity": '0'
    },
    "16-drunk-elephant-oil-67": {
        "productId": "16-drunk-elephant-oil-67",
        "imageId": 5,
        "brand": "Drunk Elephant",
        "type": "skincare",
        "name": "Virgin Marula Antioxidant Face Oil",
        "concern": "Helps reduce Fine Lines and Wrinkles, Dryness and Dullness and Uneven Texture",
        "howToUse": "Apply two to three drops evenly to face, neck, chest, hands, cuticles, backs of arms, or any place needing increased moisture without any greasy residue for balanced, glowing, healthy-looking skin.",
        "ingredients": "Sclerocarya Birrea (Marula) Seed Oil",
        "price": "72.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "17-eyeshadow-78": {
        "productId": "17-eyeshadow-78",
        "imageId": 6,
        "brand": "Lunar Beauty",
        "type": "makeup",
        "name": "Eyeshadow",
        "concern": "Does not Smudge",
        "howToUse": "Use a large fluffy brush (sold separately) for soft, transition shades.",
        "ingredients": "Free of sulfates SLS and SLES, parabens, formaldehyde-releasing agents, and phthalates. This product is also vegan, cruelty-free, and gluten-free",
        "price": "29.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "18-eyshadow2-89": {
        "productId": "18-eyshadow2-89",
        "imageId": 8,
        "brand": "Charlotte Tilbury",
        "type": "makeup",
        "name": "Luxury Eyeshadow Palette",
        "concern": "Shimmer finish and does not smudge",
        "howToUse": "To use, start by applying the Prime shade of the eyeshadow palette all over your eyelid with the Eye Blender Brush. Pop in the inner corner of your eyes to open up and widen.",
        "ingredients": "Free of sulfates. This product is gluten-free.",
        "price": "53.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "19-eyshadow3-90": {
        "productId": "19-eyshadow3-90",
        "imageId": 9,
        "brand": "Fenty Beauty By Rihanna",
        "type": "makeup",
        "name": "Moroccan Spice Eyeshadow Palette",
        "concern": "matte finish and does not smudge",
        "howToUse": "Apply shadows using the FENTY BEAUTY All-Over Eyeshadow Brush 200 and Tapered Blending Brush 210 ",
        "ingredients": "Talc, Phenoxyethanol, Octyldodecyl Stearoyl Stearate",
        "price": "29.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "20-eyeshadow4-01": {
        "productId": "20-eyeshadow4-01",
        "imageId": 7,
        "brand": "Urban Decay",
        "type": "makeup",
        "name": "Naked Reloaded Eyeshadow Palette",
        "concern": "Smooth matte to metallic finish",
        "howToUse": "Achieve the ultimate blown-out look by using a clean UD Pro Blending Brush to softly blend the outer edges—when you think you’re done blending, blend some more.",
        "ingredients": "Free of phthalates. This product is also cruelty-free.",
        "price": "44.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "21-dior-21": {
        "productId": "21-dior-21",
        "imageId": 10,
        "brand": "Dior",
        "type": "makeup",
        "name": "Rouge à Lèvres Mat Matte Lipstick",
        "concern": "lipstick has a bright and rich color and the feel is smooth, soft, and velvety.",
        "howToUse": "Apply using the sharp edge of the bullet to contour the lips.",
        "ingredients": "Octyldodecanol, Trimethylolpropane Triisostearate",
        "price": "42.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "22-shampoo-23": {
        "productId": "22-shampoo-23",
        "imageId": 11,
        "brand": "Kerastase",
        "type": "hair",
        "name": "Blond Absolu Anti-Brass Purple Shampoo",
        "concern": "Brassiness",
        "howToUse": "Start in the center of lips and smooth outwards toward corners of mouth.",
        "ingredients": "Hyaluronic Acid,Ultra-violet Neutralizers",
        "price": "35.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "23-foundation-34": {
        "productId": "23-foundation-34",
        "imageId": 12,
        "brand": "Make Up For Ever",
        "type": "makeup",
        "name": "Ultra HD Invisible Cover Foundation",
        "concern": "Natural finish",
        "howToUse": "Apply using a flat foundation brush like Artisan Brush #108 (sold separately), starting at the center and blending out and down.",
        "ingredients": "Hyaluronic Spheres: Formulated to look fresh and be comfortable all day.",
        "price": "43.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "24-mascara-45": {
        "productId": "24-mascara-45",
        "imageId": 13,
        "brand": "Marc Jacobs Beauty",
        "type": "makeup",
        "name": "Velvet Noir Major Volume Mascara",
        "concern": " look of thick, false lashes",
        "howToUse": "Apply Velvet Noir Major Volume Mascara on its own, or layer with O!Mega Lash Volumizing Mascara",
        "ingredients": "This product is cruelty-free.",
        "price": "15.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "25-setting-powder-56": {
        "productId": "25-setting-powder-56",
        "imageId": 14,
        "brand": "Laura Mercier",
        "type": "makeup",
        "name": "Translucent Loose Setting Powder",
        "concern": "makeup for long-lasting wear without adding weight or texture.",
        "howToUse": "Prep Laura Mercier’s Velour Puff (sold separately) by massaging Translucent Loose Setting Powder into the puff, folding both halves together",
        "ingredients": "Talc, Magnesium Myristate, Nylon-12, Caprylic/Capric Triglyceride",
        "price": "39.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
    "26-lipstick-ysl-67": {
        "productId": "26-lipstick-ysl-67",
        "imageId": 16,
        "brand": "YVES Saint Laurent",
        "type": "makeup",
        "name": "Rouge Pur Couture Lipstick Collection",
        "concern": "Kiss proof",
        "howToUse": "Apply Rouge Pur Couture by starting at the center of the lip and gliding towards the corners of the mouth.",
        "ingredients": "Propylene Glycol Dibenzoate, Octyldodecanol, Pentaerythrityl Tetraisostearate",
        "price": "38.00",
        "quantity": '1',
        "maxQuantity": '10'
    },
};

module.exports = {
    products
}